export { ClientForm } from './components/ClientForm'
export { ClientList } from './components/ClientList'
export { ClientDetailHeader } from './components/ClientDetailHeader'
export { ClientOverviewStats } from './components/ClientOverviewStats'
export { ClientPrimaryDetails } from './components/ClientPrimaryDetails'
export { ClientTasksCard } from './components/ClientTasksCard'
export { ClientProjectsCard } from './components/ClientProjectsCard'
export { ClientManagementHeader } from './components/ClientManagementHeader'
export { ClientDashboardHeader } from './components/ClientDashboardHeader'
export { ClientDashboardStats } from './components/ClientDashboardStats'
export { ClientDashboardTasks } from './components/ClientDashboardTasks'
export { useClients, useClient, useCreateClient, useUpdateClient, useDeleteClient } from './hooks/useClients'
export { useClientManagement } from './hooks/useClientManagement'
export { useClientDetail } from './hooks/useClientDetail'
export { useClientDashboard } from './hooks/useClientDashboard'
export { useClientProjects } from './hooks/useClientProjects'
export { useClientTasks } from './hooks/useClientTasks'
export { useClientFiles } from './hooks/useClientFiles'
export { clientSchema, defaultClientValues } from './schemas/clientSchema'
export type { ClientFormValues } from './schemas/clientSchema'
